export enum CartActionTypes {
	ADD_CART_ITEM = 'ADD_CART_ITEM',
	REMOVE_CART_ITEM = 'REMOVE_CART_ITEM',
	CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS',
	CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD',
}
