export enum OrderActionTypes {
	OREDER_CREATE_REQUEST = 'OREDER_CREATE_REQUEST',
	OREDER_CREATE_SUCCESS = 'OREDER_CREATE_SUCCESS',
	OREDER_CREATE_FAIL = 'OREDER_CREATE_FAIL',
	OREDER_DETAILS_REQUEST = 'OREDER_DETAILS_REQUEST',
	OREDER_DETAILS_SUCCESS = 'OREDER_DETAILS_SUCCESS',
	OREDER_DETAILS_FAIL = 'OREDER_DETAILS_FAIL',
	OREDER_PAY_REQUEST = 'OREDER_PAY_REQUEST',
	OREDER_PAY_SUCCESS = 'OREDER_PAY_SUCCESS',
	OREDER_PAY_FAIL = 'OREDER_PAY_FAIL',
}

export enum UserOrdersActionTypes {
	USER_OREDERS_REQUEST = 'USER_OREDERS_REQUEST',
	USER_OREDERS_SUCCESS = 'USER_OREDERS_SUCCESS',
	USER_OREDERS_FAIL = 'USER_OREDERS_FAIL',
	USER_OREDERS_RESET = 'USER_OREDERS_RESET',
}
