export enum ProductActionTypes {
	PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST',
	PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS',
	PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL',
	PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST',
	PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS',
	PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL',
}

export enum ProductDeleteActionTypes {
	PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST',
	PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS',
	PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL',
}

export enum ProductUpdateActionTypes {
	PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST',
	PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS',
	PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL',
}
