export enum UserProfileActionTypes {
	USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST',
	USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS',
	USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET',
	USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL',
}
